### ISSUE TITLE
backend server side and confirm payment

### ISSUE THREAD

**Issue by nordinenn** [LucaIaconelli/stripe-dart#1]
Hey hope you are doing well guys .
is this project workin without nodeJS backend ?
aslo how i can confirme a payment there ?

**Comment by LucaIaconelli** [comment]
Hi, 

This project is a recreation of the Stripe nodejs library in Dart. You can do everything you could do with nodejs api.

I'm also working on a library (stripe-flutter) that recreates the stripe-js designed for the client.

Thank you.

**Comment by nordinenn** [comment]
Hey thanks for your answer  , 
yeah i understand and i catch the problem is i can't use that api becuase i have just free plan in firebase . 
am i right ?

**Comment by LucaIaconelli** [comment]
Yes for external HTTP requests on Firebase Cloud Functions you need a paid plan.

**Comment by nordinenn** [comment]
yeah i see  , if i call stripe api from flutter (dart) using https request it will work right ?
so why all libaries dont use that ?

**Comment by LucaIaconelli** [comment]
Yes, you can, but this library is created for a server-side usage, not for a client because not all api can be called with a publishable stripe api. I'm also working on a client library for flutter I'll let you know when I finish

**Comment by nordinenn** [comment]
ah that's great , i hope you finish it soon .
i will be waiting bro . 
have great day and thanks again for your support

**Comment by LucaIaconelli** [comment]
Hi, 

A first version of Stripe Flutter SDK it’s ready and you can find it [here](https://pub.dev/packages/flutter_payments_stripe_sdk)

Thanks

**Comment by nordinenn** [comment]
Hi  
i saw that befor 2 days ,good job . 
can you publish an example  ? 
Thnaks have great day
