### ISSUE TITLE
Missing endpoint 'prices'

### ISSUE THREAD

**Issue by afpatmin** [LucaIaconelli/stripe-dart#4]
Hi, 
I'm trying to fetch the Prices of a Product, but it seems that endpoint is missing int stripe-dart?

https://stripe.com/docs/api/prices/list?lang=node

**Comment by LucaIaconelli** [comment]
Hi, 

I just added the endpoint prices to the library. (https://stripe.com/docs/api/prices)

Thanks

**Comment by afpatmin** [comment]
Great, thank you!
