### ISSUE TITLE
Can't expand resources

### ISSUE THREAD

**Issue by afpatmin** [LucaIaconelli/stripe-dart#5]
when attempting this;
```
final sessionData = await stripe.sessions.retrieve(session.id, params: {'expand': ['line_items']});
```
Stripe responds with an error saying ['line_items'] is not a valid array. Could it be it expects a javascript array?

https://stripe.com/docs/expand

**Comment by LucaIaconelli** [comment]
Hello,

Soon I will update the library by adding the Session endpoint for list line_items

Thank you very much
